# Generated by Django 5.0.2 on 2024-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enviar_arquivo',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
