# Generated by Django 5.0.2 on 2024-02-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_rename_description_contact_anotacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.category'),
        ),
    ]
